paypalProperties:
# sandbox mode
  clientID: AYE81vi4Et_dFzzImf1k7XDsZeUdQ9cdR0L9ufHrnrGLmcNTqRGmEidDkhzVeY30bdYnsBYv-9ahbPka
  clientSecret: EMaZL62-fRXfSvILPQSOlL-zi82qsZ8CnNPeg3ctu2zMF0ku6yqWvKBsUHNMKg7yEXnBMJyDWTOyQPBA
  mode: sandbox
# live mode
#  clientID: AcJpaxbHEWZKeBJiXtoyA6EpalyL-Xwg7vQQqH6ZB1Q68aKz4OAWbJecPMRWj1N8yOyYLFCVFYVhsD5i
#  clientSecret: ELEXxC1FxhexPHXPYty0yEpclnnOYwvZys3QBe9PReh9qjEgszVeEZV1gsysRxscpWqJOvm1hsyaD96Q
#  mode: live
